global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'surrealdb'
    static_configs:
      # Scraping SurrealDB internal health endpoint
      - targets: ['surrealdb:8000']

  - job_name: 'open_notebook'
    static_configs:
      - targets: ['open_notebook:5055']
